-- NoteTrack — schema sync. Generated by scripts/build-sync-sql.sh; do not edit by hand.
-- Safe to run repeatedly. Run the whole file in the Supabase SQL editor.
-- Built from: 21ad78b on 2026-10-03

-- ---------------------------------------------------------------
-- supabase/sync/00_legacy.sql
-- ---------------------------------------------------------------
-- ===== Sync step 0: park the v0.1 schema =============================
-- v0.1 used projects as the container (projects, people, items, pipelines…).
-- v0.2 reuses some of those table names with different columns. Nothing is
-- dropped: the old tables are moved into a `legacy` schema, which the API does
-- not expose, so the data stays queryable from the SQL editor.
do $$
declare
  t text;
  old_tables text[] := array[
    'watches','comments','subtasks','meeting_attendees','meetings','gate_moves',
    'risks','decisions','actions','entry_refs','attachments','entries','items',
    'pipeline_stages','pipelines','people','memberships','projects'
  ];
  is_v01 boolean;
begin
  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'memberships' and column_name = 'project_id'
  ) into is_v01;

  if not is_v01 then
    raise notice 'sync: no v0.1 schema found, nothing to park';
    return;
  end if;

  raise notice 'sync: v0.1 schema found — moving it to schema "legacy"';
  create schema if not exists legacy;

  foreach t in array old_tables loop
    if to_regclass('public.' || t) is not null then
      -- leave the realtime publication, if it was ever added
      begin
        execute format('alter publication supabase_realtime drop table public.%I', t);
      exception when others then null;
      end;
      execute format('alter table public.%I set schema legacy', t);
    end if;
  end loop;

  -- v0.1 RPC that only makes sense with the old tables
  drop function if exists public.create_project(text, text);

  -- v0.1 RLS helpers took (pid uuid); v0.2 redefines them as (wid uuid), and
  -- Postgres will not rename a parameter in place. Dropping them also drops the
  -- policies on the parked legacy tables, which is wanted: with RLS still on
  -- and no policies, legacy data is reachable only from the SQL editor.
  drop function if exists public.is_member(uuid) cascade;
  drop function if exists public.is_editor(uuid) cascade;
  drop function if exists public.is_owner(uuid) cascade;
end $$;

-- ---------------------------------------------------------------
-- supabase/migrations/0001_init.sql
-- ---------------------------------------------------------------
-- NoteTrack v0.2 — schema
--
-- Model: a WORKSPACE (a department) holds TABLES. A table is a named set of
-- ROWS with typed PROPERTIES. The DIARY is a stream of ENTRIES; an entry can
-- reference any row (entry_refs). Actions, Decisions, Risks, Meetings, People
-- and Projects are tables like any other, but with a `kind` so the diary knows
-- how to write to them.
--
-- Run on a fresh Supabase project. Safe to re-run (idempotent).

create extension if not exists "pg_trgm";
create extension if not exists "pgcrypto";

-- ===== WORKSPACES ====================================================
create table if not exists public.workspaces (
  id         uuid primary key default gen_random_uuid(),
  slug       text not null unique,
  name       text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.memberships (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id      uuid not null references auth.users(id) on delete cascade,
  role         text not null default 'editor' check (role in ('owner','editor','viewer')),
  created_at   timestamptz not null default now(),
  primary key (workspace_id, user_id)
);
create index if not exists memberships_user_idx on public.memberships (user_id);

-- ===== TABLES / PROPERTIES / ROWS ====================================
create table if not exists public.tables (
  id             uuid primary key default gen_random_uuid(),
  workspace_id   uuid not null references public.workspaces(id) on delete cascade,
  slug           text not null,
  name           text not null,
  kind           text not null default 'custom'
                 check (kind in ('custom','people','projects','actions','decisions','risks','meetings')),
  ref_prefix     text not null,
  next_seq       integer not null default 1,
  is_stub_target boolean not null default false,
  sort_order     smallint not null default 0,
  created_at     timestamptz not null default now(),
  unique (workspace_id, slug)
);
-- one table per system kind per workspace
create unique index if not exists tables_system_kind_idx
  on public.tables (workspace_id, kind) where kind <> 'custom';

create table if not exists public.properties (
  id                uuid primary key default gen_random_uuid(),
  table_id          uuid not null references public.tables(id) on delete cascade,
  key               text not null,
  name              text not null,
  type              text not null
                    check (type in ('text','number','select','multi_select','date','person','relation','checkbox','url')),
  options           jsonb not null default '[]'::jsonb,   -- select/multi_select: ["a","b"]
  relation_table_id uuid references public.tables(id) on delete set null,
  show_in_list      boolean not null default true,
  sort_order        smallint not null default 0,
  created_at        timestamptz not null default now(),
  unique (table_id, key)
);

create table if not exists public.rows (
  id              uuid primary key default gen_random_uuid(),
  workspace_id    uuid not null references public.workspaces(id) on delete cascade,
  table_id        uuid not null references public.tables(id) on delete cascade,
  ref_code        text not null,
  title           text not null,
  props           jsonb not null default '{}'::jsonb,
  user_id         uuid references auth.users(id) on delete set null,  -- people rows only
  source_entry_id uuid,                                               -- actions/decisions/risks created from the diary
  archived_at     timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (workspace_id, ref_code)
);
create index if not exists rows_table_idx on public.rows (table_id, updated_at desc);
create index if not exists rows_title_trgm_idx on public.rows using gin (title gin_trgm_ops);
create index if not exists rows_props_idx on public.rows using gin (props);
create index if not exists rows_user_idx on public.rows (user_id) where user_id is not null;
create index if not exists rows_source_entry_idx on public.rows (source_entry_id) where source_entry_id is not null;

-- ===== ENTRIES (the diary) ===========================================
create table if not exists public.entries (
  id             uuid primary key default gen_random_uuid(),
  workspace_id   uuid not null references public.workspaces(id) on delete cascade,
  author_id      uuid references auth.users(id) on delete set null,
  type           text not null check (type in ('note','action','decision','risk','gate','meeting','call')),
  body_md        text not null default '',
  occurred_at    timestamptz not null default now(),
  meeting_row_id uuid references public.rows(id) on delete set null,
  project_row_id uuid references public.rows(id) on delete set null,
  edited_at      timestamptz,
  struck_at      timestamptz,
  search_tsv     tsvector generated always as (to_tsvector('simple', coalesce(body_md, ''))) stored,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists entries_ws_occurred_idx on public.entries (workspace_id, occurred_at desc);
create index if not exists entries_search_idx on public.entries using gin (search_tsv);
create index if not exists entries_meeting_idx on public.entries (meeting_row_id) where meeting_row_id is not null;
create index if not exists entries_project_idx on public.entries (project_row_id) where project_row_id is not null;

alter table public.rows
  drop constraint if exists rows_source_entry_fk;
alter table public.rows
  add constraint rows_source_entry_fk
  foreign key (source_entry_id) references public.entries(id) on delete cascade;

-- previous bodies, kept when an entry is edited
create table if not exists public.entry_revisions (
  id          uuid primary key default gen_random_uuid(),
  entry_id    uuid not null references public.entries(id) on delete cascade,
  body_md     text not null,
  replaced_at timestamptz not null default now(),
  edited_by   uuid references auth.users(id) on delete set null
);
create index if not exists entry_revisions_entry_idx on public.entry_revisions (entry_id, replaced_at desc);

-- links from an entry to any row (#refs and @mentions alike)
create table if not exists public.entry_refs (
  entry_id uuid not null references public.entries(id) on delete cascade,
  row_id   uuid not null references public.rows(id) on delete cascade,
  primary key (entry_id, row_id)
);
create index if not exists entry_refs_row_idx on public.entry_refs (row_id);

create table if not exists public.attachments (
  id           uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  entry_id     uuid not null references public.entries(id) on delete cascade,
  kind         text not null default 'file' check (kind in ('file','ink')),
  file_path    text not null,
  mime         text,
  bytes        bigint,
  meta         jsonb not null default '{}'::jsonb,   -- ink: { strokes_path, width, height }
  created_at   timestamptz not null default now()
);
create index if not exists attachments_entry_idx on public.attachments (entry_id);

-- ===== VIEWS (saved filters/sort/group per table) ====================
create table if not exists public.views (
  id         uuid primary key default gen_random_uuid(),
  table_id   uuid not null references public.tables(id) on delete cascade,
  name       text not null,
  layout     text not null default 'list' check (layout in ('list','board')),
  config     jsonb not null default '{}'::jsonb,  -- { filters:[{key,op,value}], sort:{key,dir}, group:key }
  pinned     boolean not null default false,      -- shown at the top of the sidebar
  sort_order smallint not null default 0,
  created_at timestamptz not null default now()
);
alter table public.views add column if not exists pinned boolean not null default false;
create index if not exists views_table_idx on public.views (table_id, sort_order);

-- ===== TRIGGERS ======================================================
create or replace function public.touch_updated_at() returns trigger
language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists rows_touch on public.rows;
create trigger rows_touch before update on public.rows
  for each row execute procedure public.touch_updated_at();

drop trigger if exists entries_touch on public.entries;
create trigger entries_touch before update on public.entries
  for each row execute procedure public.touch_updated_at();

-- Assign a ref code (PREFIX-N) when none is supplied.
create or replace function public.rows_assign_ref() returns trigger
language plpgsql as $$
declare
  v_prefix text;
  v_seq integer;
begin
  if new.ref_code is null or btrim(new.ref_code) = '' then
    update public.tables
      set next_seq = next_seq + 1
      where id = new.table_id
      returning ref_prefix, next_seq - 1 into v_prefix, v_seq;
    new.ref_code := v_prefix || '-' || v_seq;
  else
    new.ref_code := btrim(new.ref_code);
  end if;
  return new;
end $$;

drop trigger if exists rows_assign_ref on public.rows;
create trigger rows_assign_ref before insert on public.rows
  for each row execute procedure public.rows_assign_ref();

-- ===== RLS HELPERS ===================================================
create or replace function public.is_member(wid uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.memberships m where m.workspace_id = wid and m.user_id = auth.uid());
$$;

create or replace function public.is_editor(wid uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.memberships m
    where m.workspace_id = wid and m.user_id = auth.uid() and m.role in ('owner','editor'));
$$;

create or replace function public.is_owner(wid uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.memberships m
    where m.workspace_id = wid and m.user_id = auth.uid() and m.role = 'owner');
$$;

create or replace function public.table_workspace(tid uuid) returns uuid
language sql stable security definer set search_path = public as $$
  select workspace_id from public.tables where id = tid;
$$;

create or replace function public.entry_workspace(eid uuid) returns uuid
language sql stable security definer set search_path = public as $$
  select workspace_id from public.entries where id = eid;
$$;

-- ===== RLS ===========================================================
alter table public.workspaces      enable row level security;
alter table public.memberships     enable row level security;
alter table public.tables          enable row level security;
alter table public.properties      enable row level security;
alter table public.rows            enable row level security;
alter table public.entries         enable row level security;
alter table public.entry_revisions enable row level security;
alter table public.entry_refs      enable row level security;
alter table public.attachments     enable row level security;
alter table public.views           enable row level security;

drop policy if exists workspaces_read on public.workspaces;
create policy workspaces_read on public.workspaces for select using (public.is_member(id));
drop policy if exists workspaces_update on public.workspaces;
create policy workspaces_update on public.workspaces for update
  using (public.is_owner(id)) with check (public.is_owner(id));

drop policy if exists memberships_read on public.memberships;
create policy memberships_read on public.memberships for select
  using (user_id = auth.uid() or public.is_member(workspace_id));
drop policy if exists memberships_owner_write on public.memberships;
create policy memberships_owner_write on public.memberships for all
  using (public.is_owner(workspace_id)) with check (public.is_owner(workspace_id));

-- tables with a workspace_id column: members read, editors write
drop policy if exists tables_read on public.tables;
create policy tables_read on public.tables for select using (public.is_member(workspace_id));
drop policy if exists tables_write on public.tables;
create policy tables_write on public.tables for all
  using (public.is_editor(workspace_id)) with check (public.is_editor(workspace_id));

drop policy if exists rows_read on public.rows;
create policy rows_read on public.rows for select using (public.is_member(workspace_id));
drop policy if exists rows_write on public.rows;
create policy rows_write on public.rows for all
  using (public.is_editor(workspace_id)) with check (public.is_editor(workspace_id));

drop policy if exists entries_read on public.entries;
create policy entries_read on public.entries for select using (public.is_member(workspace_id));
drop policy if exists entries_write on public.entries;
create policy entries_write on public.entries for all
  using (public.is_editor(workspace_id)) with check (public.is_editor(workspace_id));

drop policy if exists attachments_read on public.attachments;
create policy attachments_read on public.attachments for select using (public.is_member(workspace_id));
drop policy if exists attachments_write on public.attachments;
create policy attachments_write on public.attachments for all
  using (public.is_editor(workspace_id)) with check (public.is_editor(workspace_id));

-- joined through tables
drop policy if exists properties_read on public.properties;
create policy properties_read on public.properties for select
  using (public.is_member(public.table_workspace(table_id)));
drop policy if exists properties_write on public.properties;
create policy properties_write on public.properties for all
  using (public.is_editor(public.table_workspace(table_id)))
  with check (public.is_editor(public.table_workspace(table_id)));

drop policy if exists views_read on public.views;
create policy views_read on public.views for select
  using (public.is_member(public.table_workspace(table_id)));
drop policy if exists views_write on public.views;
create policy views_write on public.views for all
  using (public.is_editor(public.table_workspace(table_id)))
  with check (public.is_editor(public.table_workspace(table_id)));

-- joined through entries
drop policy if exists entry_revisions_read on public.entry_revisions;
create policy entry_revisions_read on public.entry_revisions for select
  using (public.is_member(public.entry_workspace(entry_id)));
drop policy if exists entry_revisions_write on public.entry_revisions;
create policy entry_revisions_write on public.entry_revisions for all
  using (public.is_editor(public.entry_workspace(entry_id)))
  with check (public.is_editor(public.entry_workspace(entry_id)));

drop policy if exists entry_refs_read on public.entry_refs;
create policy entry_refs_read on public.entry_refs for select
  using (public.is_member(public.entry_workspace(entry_id)));
drop policy if exists entry_refs_write on public.entry_refs;
create policy entry_refs_write on public.entry_refs for all
  using (public.is_editor(public.entry_workspace(entry_id)))
  with check (public.is_editor(public.entry_workspace(entry_id)));

-- ===== REALTIME ======================================================
-- Add the diary tables to the realtime publication so open pages refresh.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.entries;
    exception when duplicate_object then null; end;
    begin
      alter publication supabase_realtime add table public.rows;
    exception when duplicate_object then null; end;
  end if;
end $$;

-- ---------------------------------------------------------------
-- supabase/migrations/0002_functions.sql
-- ---------------------------------------------------------------
-- NoteTrack v0.2 — RPCs
--   create_workspace(name, slug, with_sample)  → seeds system tables, properties, views, your People row
--   add_member_by_email(workspace_id, email, role) → adds an existing user as a member
--   search_workspace(workspace_id, q) → full-text search across entries and rows
-- All are security definer because the caller may not yet have a membership row.

-- ---------------------------------------------------------------------
-- helper: insert a property
create or replace function public._add_property(
  p_table uuid, p_key text, p_name text, p_type text,
  p_options jsonb default '[]'::jsonb, p_relation uuid default null, p_sort int default 0
) returns uuid language plpgsql as $$
declare v_id uuid;
begin
  insert into public.properties (table_id, key, name, type, options, relation_table_id, sort_order)
  values (p_table, p_key, p_name, p_type, p_options, p_relation, p_sort)
  on conflict (table_id, key) do update set name = excluded.name
  returning id into v_id;
  return v_id;
end $$;

-- ---------------------------------------------------------------------
-- helper: create the system tables for a workspace
create or replace function public._seed_system_tables(p_ws uuid) returns void
language plpgsql as $$
declare
  t_projects uuid; t_people uuid; t_actions uuid; t_decisions uuid; t_risks uuid;
  t_meetings uuid; t_items uuid; t_stake uuid;
begin
  insert into public.tables (workspace_id, slug, name, kind, ref_prefix, sort_order)
  values (p_ws, 'projects', 'Projects', 'projects', 'PRJ', 1) returning id into t_projects;
  insert into public.tables (workspace_id, slug, name, kind, ref_prefix, sort_order)
  values (p_ws, 'people', 'People', 'people', 'PPL', 2) returning id into t_people;
  insert into public.tables (workspace_id, slug, name, kind, ref_prefix, sort_order, is_stub_target)
  values (p_ws, 'items', 'Items', 'custom', 'ITM', 3, true) returning id into t_items;
  insert into public.tables (workspace_id, slug, name, kind, ref_prefix, sort_order)
  values (p_ws, 'actions', 'Actions', 'actions', 'ACT', 4) returning id into t_actions;
  insert into public.tables (workspace_id, slug, name, kind, ref_prefix, sort_order)
  values (p_ws, 'decisions', 'Decisions', 'decisions', 'DEC', 5) returning id into t_decisions;
  insert into public.tables (workspace_id, slug, name, kind, ref_prefix, sort_order)
  values (p_ws, 'risks', 'Risks', 'risks', 'RSK', 6) returning id into t_risks;
  insert into public.tables (workspace_id, slug, name, kind, ref_prefix, sort_order)
  values (p_ws, 'meetings', 'Meetings', 'meetings', 'MTG', 7) returning id into t_meetings;
  insert into public.tables (workspace_id, slug, name, kind, ref_prefix, sort_order)
  values (p_ws, 'stakeholders', 'Stakeholders', 'custom', 'STK', 8) returning id into t_stake;

  -- Projects
  perform public._add_property(t_projects, 'status', 'Status', 'select', '["active","on hold","closed"]', null, 1);
  perform public._add_property(t_projects, 'phase', 'Phase', 'text', '[]', null, 2);
  perform public._add_property(t_projects, 'client', 'Client', 'text', '[]', null, 3);
  perform public._add_property(t_projects, 'lead', 'Lead', 'person', '[]', null, 4);

  -- People
  perform public._add_property(t_people, 'role', 'Role', 'text', '[]', null, 1);
  perform public._add_property(t_people, 'org', 'Organisation', 'text', '[]', null, 2);
  perform public._add_property(t_people, 'email', 'Email', 'text', '[]', null, 3);

  -- Items (default stub target for unknown #refs)
  perform public._add_property(t_items, 'kind', 'Kind', 'select', '["equipment","document","area","other"]', null, 1);
  perform public._add_property(t_items, 'stage', 'Stage', 'select',
    '["Concept","Design","Procurement","Fabrication","FAT","Shipping","Install","Commission"]', null, 2);
  perform public._add_property(t_items, 'owner', 'Owner', 'person', '[]', null, 3);
  perform public._add_property(t_items, 'project', 'Project', 'relation', '[]', t_projects, 4);

  -- Actions (written by /todo /action /done)
  perform public._add_property(t_actions, 'status', 'Status', 'select', '["open","in progress","blocked","done"]', null, 1);
  perform public._add_property(t_actions, 'owner', 'Owner', 'person', '[]', null, 2);
  perform public._add_property(t_actions, 'due', 'Due', 'date', '[]', null, 3);
  perform public._add_property(t_actions, 'project', 'Project', 'relation', '[]', t_projects, 4);

  -- Decisions (written by /decision)
  perform public._add_property(t_decisions, 'status', 'Status', 'select', '["proposed","approved","rejected"]', null, 1);
  perform public._add_property(t_decisions, 'decided_by', 'Decided by', 'person', '[]', null, 2);
  perform public._add_property(t_decisions, 'project', 'Project', 'relation', '[]', t_projects, 3);

  -- Risks (written by /risk)
  perform public._add_property(t_risks, 'probability', 'Probability', 'number', '[]', null, 1);
  perform public._add_property(t_risks, 'impact', 'Impact', 'number', '[]', null, 2);
  perform public._add_property(t_risks, 'status', 'Status', 'select', '["open","mitigating","closed"]', null, 3);
  perform public._add_property(t_risks, 'owner', 'Owner', 'person', '[]', null, 4);
  perform public._add_property(t_risks, 'project', 'Project', 'relation', '[]', t_projects, 5);

  -- Meetings
  perform public._add_property(t_meetings, 'date', 'Date', 'date', '[]', null, 1);
  perform public._add_property(t_meetings, 'status', 'Status', 'select', '["live","ended"]', null, 2);
  perform public._add_property(t_meetings, 'project', 'Project', 'relation', '[]', t_projects, 3);

  -- Stakeholders
  perform public._add_property(t_stake, 'org', 'Organisation', 'text', '[]', null, 1);
  perform public._add_property(t_stake, 'role', 'Role', 'text', '[]', null, 2);
  perform public._add_property(t_stake, 'influence', 'Influence', 'select', '["low","medium","high"]', null, 3);
  perform public._add_property(t_stake, 'project', 'Project', 'relation', '[]', t_projects, 4);

  -- Default saved views
  insert into public.views (table_id, name, layout, config, pinned, sort_order) values
    (t_actions, 'On me', 'list',
      '{"filters":[{"key":"owner","op":"eq","value":"@me"},{"key":"status","op":"neq","value":"done"}],"sort":{"key":"due","dir":"asc"}}', true, 0);
  insert into public.views (table_id, name, layout, config, sort_order) values
    (t_actions, 'Open', 'list',
      '{"filters":[{"key":"status","op":"neq","value":"done"}],"sort":{"key":"due","dir":"asc"}}', 1),
    (t_actions, 'By status', 'board', '{"group":"status"}', 2),
    (t_items, 'By stage', 'board', '{"group":"stage"}', 1),
    (t_risks, 'Open', 'list',
      '{"filters":[{"key":"status","op":"neq","value":"closed"}],"sort":{"key":"probability","dir":"desc"}}', 1),
    (t_projects, 'Active', 'list', '{"filters":[{"key":"status","op":"eq","value":"active"}]}', 1);
end $$;

-- ---------------------------------------------------------------------
-- helper: sample content (a small engineering project) for a workspace
create or replace function public._seed_sample(p_ws uuid, p_uid uuid) returns void
language plpgsql as $$
declare
  t_projects uuid; t_people uuid; t_items uuid; t_actions uuid; t_risks uuid; t_decisions uuid; t_stake uuid;
  r_proj uuid; r_sk uuid; r_mr uuid; r_pv uuid; r_lr uuid; r_me uuid;
  r_sag uuid; r_cv uuid; r_pmp uuid; r_swg uuid; r_pid uuid;
  e uuid; a uuid;
begin
  select id into t_projects  from public.tables where workspace_id = p_ws and kind = 'projects';
  select id into t_people    from public.tables where workspace_id = p_ws and kind = 'people';
  select id into t_actions   from public.tables where workspace_id = p_ws and kind = 'actions';
  select id into t_risks     from public.tables where workspace_id = p_ws and kind = 'risks';
  select id into t_decisions from public.tables where workspace_id = p_ws and kind = 'decisions';
  select id into t_items     from public.tables where workspace_id = p_ws and slug = 'items';
  select id into t_stake     from public.tables where workspace_id = p_ws and slug = 'stakeholders';
  select id into r_me from public.rows where table_id = t_people and user_id = p_uid;

  insert into public.rows (workspace_id, table_id, ref_code, title, props)
  values (p_ws, t_projects, 'SP-2', 'South Plant — Phase 2',
    jsonb_build_object('status','active','phase','Detail design','client','Northern Minerals','lead', r_me))
  returning id into r_proj;

  insert into public.rows (workspace_id, table_id, ref_code, title, props) values
    (p_ws, t_people, 'sk', 'Sarah K.', '{"role":"Process engineer","org":"In-house"}') returning id into r_sk;
  insert into public.rows (workspace_id, table_id, ref_code, title, props) values
    (p_ws, t_people, 'mr', 'Marc R.', '{"role":"Mechanical lead","org":"In-house"}') returning id into r_mr;
  insert into public.rows (workspace_id, table_id, ref_code, title, props) values
    (p_ws, t_people, 'pv', 'Pavel V.', '{"role":"Vendor engineer","org":"Outotec"}') returning id into r_pv;
  insert into public.rows (workspace_id, table_id, ref_code, title, props) values
    (p_ws, t_people, 'lr', 'Leo R.', '{"role":"Instrumentation & control","org":"In-house"}') returning id into r_lr;

  insert into public.rows (workspace_id, table_id, ref_code, title, props) values
    (p_ws, t_stake, 'STK-1', 'Diane N.', jsonb_build_object('org','EPCM','role','Client representative','influence','high','project',r_proj)),
    (p_ws, t_stake, 'STK-2', 'Environmental regulator', jsonb_build_object('org','State EPA','role','Approvals','influence','high','project',r_proj));

  insert into public.rows (workspace_id, table_id, ref_code, title, props) values
    (p_ws, t_items, 'SAG-mill', 'SAG mill area', jsonb_build_object('kind','area','stage','Design','owner',r_mr,'project',r_proj)) returning id into r_sag;
  insert into public.rows (workspace_id, table_id, ref_code, title, props) values
    (p_ws, t_items, 'CV-203', 'CV-203 conveyor', jsonb_build_object('kind','equipment','stage','Fabrication','owner',r_mr,'project',r_proj)) returning id into r_cv;
  insert into public.rows (workspace_id, table_id, ref_code, title, props) values
    (p_ws, t_items, 'PMP-101', 'PMP-101 pump skid', jsonb_build_object('kind','equipment','stage','Shipping','owner',r_sk,'project',r_proj)) returning id into r_pmp;
  insert into public.rows (workspace_id, table_id, ref_code, title, props) values
    (p_ws, t_items, 'SWG-401', 'HV switchgear', jsonb_build_object('kind','equipment','stage','Procurement','owner',r_lr,'project',r_proj)) returning id into r_swg;
  insert into public.rows (workspace_id, table_id, ref_code, title, props) values
    (p_ws, t_items, 'PID-D', 'P&ID rev D', jsonb_build_object('kind','document','stage','Design','owner',r_pv,'project',r_proj)) returning id into r_pid;

  -- a few diary entries, oldest first
  insert into public.entries (workspace_id, author_id, type, body_md, occurred_at, project_row_id)
  values (p_ws, p_uid, 'note', 'Walked the SAG mill plinth pour — looks clean. #SAG-mill', now() - interval '2 days 6 hours', r_proj)
  returning id into e;
  insert into public.entry_refs values (e, r_sag);

  insert into public.entries (workspace_id, author_id, type, body_md, occurred_at, project_row_id)
  values (p_ws, p_uid, 'gate', 'Moved #CV-203 to Fabrication (from Procurement)', now() - interval '2 days 4 hours', r_proj)
  returning id into e;
  insert into public.entry_refs values (e, r_cv);

  insert into public.entries (workspace_id, author_id, type, body_md, occurred_at, project_row_id)
  values (p_ws, p_uid, 'action', 'Markup pump curves on #PMP-101 datasheet for @sk', now() - interval '1 day 5 hours', r_proj)
  returning id into e;
  insert into public.entry_refs values (e, r_pmp), (e, r_sk);
  insert into public.rows (workspace_id, table_id, title, props, source_entry_id)
  values (p_ws, t_actions, 'Markup pump curves on #PMP-101 datasheet for @sk',
    jsonb_build_object('status','open','owner',r_me,'due',to_char(now() + interval '2 days','YYYY-MM-DD'),'project',r_proj), e);

  insert into public.entries (workspace_id, author_id, type, body_md, occurred_at, project_row_id)
  values (p_ws, p_uid, 'decision', 'Switch gearbox vendor on #SAG-mill from Flender to Siemens', now() - interval '1 day 3 hours', r_proj)
  returning id into e;
  insert into public.entry_refs values (e, r_sag);
  insert into public.rows (workspace_id, table_id, title, props, source_entry_id)
  values (p_ws, t_decisions, 'Switch gearbox vendor on #SAG-mill from Flender to Siemens',
    jsonb_build_object('status','approved','decided_by',r_me,'project',r_proj), e);

  insert into public.entries (workspace_id, author_id, type, body_md, occurred_at, project_row_id)
  values (p_ws, p_uid, 'risk', 'Late delivery of HV switchgear #SWG-401 — 5 week lead time slip @lr', now() - interval '1 day 2 hours', r_proj)
  returning id into e;
  insert into public.entry_refs values (e, r_swg), (e, r_lr);
  insert into public.rows (workspace_id, table_id, title, props, source_entry_id)
  values (p_ws, t_risks, 'Late delivery of HV switchgear #SWG-401 — 5 week lead time slip @lr',
    jsonb_build_object('probability',4,'impact',4,'status','open','owner',r_lr,'project',r_proj), e);

  insert into public.entries (workspace_id, author_id, type, body_md, occurred_at, project_row_id)
  values (p_ws, p_uid, 'note', '@pv sent revised #PID-D — needs review before Friday.', now() - interval '3 hours', r_proj)
  returning id into e;
  insert into public.entry_refs values (e, r_pid), (e, r_pv);

  insert into public.entries (workspace_id, author_id, type, body_md, occurred_at, project_row_id)
  values (p_ws, p_uid, 'action', 'Reply to regulator on dust assessment #SWG-401', now() - interval '1 hour', r_proj)
  returning id into e;
  insert into public.entry_refs values (e, r_swg);
  insert into public.rows (workspace_id, table_id, title, props, source_entry_id)
  values (p_ws, t_actions, 'Reply to regulator on dust assessment #SWG-401',
    jsonb_build_object('status','open','owner',r_me,'due',to_char(now(),'YYYY-MM-DD'),'project',r_proj), e);
end $$;

-- ---------------------------------------------------------------------
create or replace function public.create_workspace(p_name text, p_slug text, p_sample boolean default false)
returns public.workspaces
language plpgsql security definer set search_path = public as $$
declare
  v_uid uuid := auth.uid();
  v_ws public.workspaces;
  v_slug text;
  v_email text;
  v_short text;
  t_people uuid;
begin
  if v_uid is null then raise exception 'not authenticated' using errcode = '42501'; end if;
  if p_name is null or btrim(p_name) = '' then raise exception 'name is required' using errcode = '22023'; end if;

  v_slug := lower(regexp_replace(coalesce(nullif(btrim(p_slug), ''), p_name), '[^a-zA-Z0-9]+', '-', 'g'));
  v_slug := trim(both '-' from v_slug);
  if v_slug = '' then v_slug := 'ws-' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 6); end if;

  insert into public.workspaces (slug, name) values (v_slug, btrim(p_name)) returning * into v_ws;
  insert into public.memberships (workspace_id, user_id, role) values (v_ws.id, v_uid, 'owner');

  perform public._seed_system_tables(v_ws.id);

  -- a People row for the creator, so @me and ownership work
  select email into v_email from auth.users where id = v_uid;
  v_short := lower(regexp_replace(split_part(coalesce(v_email, 'me'), '@', 1), '[^a-zA-Z0-9]', '', 'g'));
  if v_short = '' then v_short := 'me'; end if;
  select id into t_people from public.tables where workspace_id = v_ws.id and kind = 'people';
  insert into public.rows (workspace_id, table_id, ref_code, title, props, user_id)
  values (v_ws.id, t_people, substr(v_short, 1, 16), coalesce(v_email, 'Me'),
          jsonb_build_object('email', v_email), v_uid);

  if p_sample then perform public._seed_sample(v_ws.id, v_uid); end if;

  return v_ws;
end $$;

revoke all on function public.create_workspace(text, text, boolean) from public;
grant execute on function public.create_workspace(text, text, boolean) to authenticated;

-- ---------------------------------------------------------------------
-- Add someone who has already signed in at least once. No email is sent.
create or replace function public.add_member_by_email(p_ws uuid, p_email text, p_role text default 'editor')
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_user uuid;
  t_people uuid;
  v_short text;
begin
  if not public.is_owner(p_ws) then raise exception 'only owners can add members' using errcode = '42501'; end if;
  if p_role not in ('owner','editor','viewer') then raise exception 'bad role' using errcode = '22023'; end if;

  select id into v_user from auth.users where lower(email) = lower(btrim(p_email));
  if v_user is null then
    raise exception 'No user with that email has signed in yet.' using errcode = 'P0002';
  end if;

  insert into public.memberships (workspace_id, user_id, role) values (p_ws, v_user, p_role)
  on conflict (workspace_id, user_id) do update set role = excluded.role;

  select id into t_people from public.tables where workspace_id = p_ws and kind = 'people';
  if not exists (select 1 from public.rows where table_id = t_people and user_id = v_user) then
    v_short := lower(regexp_replace(split_part(p_email, '@', 1), '[^a-zA-Z0-9]', '', 'g'));
    if exists (select 1 from public.rows where workspace_id = p_ws and ref_code = v_short) then v_short := null; end if;
    insert into public.rows (workspace_id, table_id, ref_code, title, props, user_id)
    values (p_ws, t_people, v_short, btrim(p_email), jsonb_build_object('email', btrim(p_email)), v_user);
  end if;
  return v_user;
end $$;

revoke all on function public.add_member_by_email(uuid, text, text) from public;
grant execute on function public.add_member_by_email(uuid, text, text) to authenticated;

-- ---------------------------------------------------------------------
-- Full-text search across entries (tsvector) and rows (trigram on title/ref).
create or replace function public.search_workspace(p_ws uuid, p_q text, p_limit int default 40)
returns table (
  kind text, id uuid, ref_code text, title text, snippet text, occurred_at timestamptz, rank real
)
language sql stable security definer set search_path = public as $$
  with q as (select websearch_to_tsquery('simple', p_q) as tsq),
  ents as (
    select 'entry'::text as kind, e.id, null::text as ref_code, e.type as title,
           ts_headline('simple', e.body_md, q.tsq, 'MaxWords=24, MinWords=12, StartSel=**, StopSel=**') as snippet,
           e.occurred_at, ts_rank(e.search_tsv, q.tsq) as rank
    from public.entries e, q
    where e.workspace_id = p_ws and public.is_member(p_ws) and e.search_tsv @@ q.tsq
    order by rank desc, e.occurred_at desc
    limit p_limit
  ),
  rws as (
    select 'row'::text as kind, r.id, r.ref_code, r.title, t.name as snippet, r.updated_at as occurred_at,
           greatest(similarity(r.title, p_q), similarity(r.ref_code, p_q))::real as rank
    from public.rows r join public.tables t on t.id = r.table_id
    where r.workspace_id = p_ws and public.is_member(p_ws) and r.archived_at is null
      and (r.title ilike '%' || p_q || '%' or r.ref_code ilike '%' || p_q || '%')
    order by rank desc
    limit p_limit
  )
  select * from rws union all select * from ents;
$$;

revoke all on function public.search_workspace(uuid, text, int) from public;
grant execute on function public.search_workspace(uuid, text, int) to authenticated;

-- ---------------------------------------------------------------
-- supabase/migrations/0003_storage.sql
-- ---------------------------------------------------------------
-- Storage bucket for attachments (files and ink sketches).
-- Object paths start with `<workspace_id>/`; membership on that workspace grants access.

insert into storage.buckets (id, name, public, file_size_limit)
values ('attachments', 'attachments', false, 52428800)
on conflict (id) do nothing;

drop policy if exists "attachments_read_member" on storage.objects;
create policy "attachments_read_member" on storage.objects
  for select using (
    bucket_id = 'attachments'
    and exists (
      select 1 from public.memberships m
      where m.user_id = auth.uid()
        and m.workspace_id::text = split_part(storage.objects.name, '/', 1)
    )
  );

drop policy if exists "attachments_write_editor" on storage.objects;
create policy "attachments_write_editor" on storage.objects
  for insert with check (
    bucket_id = 'attachments'
    and exists (
      select 1 from public.memberships m
      where m.user_id = auth.uid()
        and m.workspace_id::text = split_part(storage.objects.name, '/', 1)
        and m.role in ('owner','editor')
    )
  );

drop policy if exists "attachments_delete_editor" on storage.objects;
create policy "attachments_delete_editor" on storage.objects
  for delete using (
    bucket_id = 'attachments'
    and exists (
      select 1 from public.memberships m
      where m.user_id = auth.uid()
        and m.workspace_id::text = split_part(storage.objects.name, '/', 1)
        and m.role in ('owner','editor')
    )
  );

-- ---------------------------------------------------------------
-- supabase/sync/99_catchup.sql
-- ---------------------------------------------------------------
-- ===== Sync step 9: catch existing v0.2 workspaces up ================
-- Seeds only run for new workspaces. Anything added to the seed later is
-- applied here to workspaces that already exist, guarded so it is idempotent.
do $$
declare
  ws record;
  t_actions uuid;
begin
  for ws in select id from public.workspaces loop
    select id into t_actions from public.tables where workspace_id = ws.id and kind = 'actions';
    if t_actions is not null and not exists (
      select 1 from public.views where table_id = t_actions and name = 'On me'
    ) then
      insert into public.views (table_id, name, layout, config, pinned, sort_order)
      values (t_actions, 'On me', 'list',
        '{"filters":[{"key":"owner","op":"eq","value":"@me"},{"key":"status","op":"neq","value":"done"}],"sort":{"key":"due","dir":"asc"}}',
        true, 0);
    end if;
  end loop;
end $$;

select 'NoteTrack schema is current.' as result;

