#!/usr/bin/env bash
# Builds supabase/sync.sql: one file to paste into the Supabase SQL editor that
# brings any existing project (v0.1, an older v0.2, or empty) up to the current schema.
set -euo pipefail
cd "$(dirname "$0")/.."
out=supabase/sync.sql
{
  echo "-- NoteTrack — schema sync. Generated by scripts/build-sync-sql.sh; do not edit by hand."
  echo "-- Safe to run repeatedly. Run the whole file in the Supabase SQL editor."
  echo "-- Built from: $(git rev-parse --short HEAD 2>/dev/null || echo 'working tree') on $(date -u +%Y-%m-%d)"
  echo
  for f in supabase/sync/00_legacy.sql supabase/migrations/*.sql supabase/sync/99_catchup.sql; do
    echo "-- ---------------------------------------------------------------"
    echo "-- $f"
    echo "-- ---------------------------------------------------------------"
    cat "$f"
    echo
  done
} > "$out"
echo "wrote $out ($(wc -l < "$out") lines)"
